name: marvie_ui_kit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  flutter_staggered_grid_view: ^0.3.0
  carousel_slider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/icons/
   - assets/images/

  fonts:
    - family: Sf_pro_display
      fonts:
        - asset: assets/fonts/Sf_pro_display/sf-pro-display-regular.ttf
        - asset: assets/fonts/Sf_pro_display/sf-pro-display-medium.otf
        - asset: assets/fonts/Sf_pro_display/sf-pro-display-bold.ttf
        - asset: assets/fonts/Sf_pro_display/sf-pro-display-semibold.otf